name: aakriti
description: AakritiQR
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.15.10
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  qr_code_scanner:
    path: ../

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.ico"


flutter:
  uses-material-design: true
  fonts:
    - family: Bangers
      fonts:
        - asset: fonts/bangers-Regular.ttf
        - weight: 700
